### ISSUE TITLE
Add required envs

### ISSUE THREAD

**Issue by ezbc** [capless/envs#14]
I would like to be specify envs as required so that if a an environment variable is missing a warning or an error is thrown.

**Comment by thelittlebug** [comment]
this should already be possible
```
>>> PAGE_CACHE=env("PAGE_CACHE", 0, "integer", allow_none=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tlb/.cache/pypoetry/virtualenvs/homepage-B7IEgj7y-py3.8/lib/python3.8/site-packages/envs/__init__.py", line 52, in __call__
    raise EnvsValueException('{}: Environment Variable Not Set'.format(key))
envs.exceptions.EnvsValueException: PAGE_CACHE: Environment Variable Not Set
